Repository neulsom-EZY/EZY-ios, pull requests merged in 2021-09, with the labels that each got.

#104 Hotfix/file structure
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/ErrandCalendarViewController.swift
  EZY/Controllers/PersonalCalendarViewController.swift
  EZY/Controllers/ShowPlanViewController.swift
  EZY/Controllers/TeamCalendarViewController.swift
  EZY/Models/ManageData.swift
  EZY/Utils/extensions.swift
  EZY/Views/AlarmManagementButton.swift
Labels: urgent, code-review, hotfix, complete

#105 Extension, Utilities path changed
  EZY.xcodeproj/project.pbxproj
  EZY/Utils/Extension.swift
  EZY/Utils/Utilities.swift
Labels: urgent, code-review, hotfix, complete

#106 ViewModel path changed
  EZY.xcodeproj/project.pbxproj
  EZY/ViewModels/ViewModel.swift
Labels: bug, urgent, code-review, hotfix, complete

#107 GoogleService-Info.plist path changed
  EZY.xcodeproj/project.pbxproj
  EZY/Resources/GoogleService-Info.plist
Labels: bug, urgent, code-review, hotfix, complete

#112 [UPDATE] EZY_color added, dynamic font changed
  EZY/Controllers/ErrandCalendarViewController.swift
  EZY/Controllers/PersonalCalendarViewController.swift
  EZY/Controllers/PushNotificationManagementViewController.swift
  EZY/Controllers/TeamCalendarViewController.swift
  EZY/Utils/Extension.swift
  EZY/Views/AlarmManagementButton.swift
  EZY/Views/CustomManagePushNotificationCell.swift
Labels: bug, urgent, code-review, hotfix, complete

#103 Feature/tag setting
  EZY/Controllers/TagManagementViewController.swift
  EZY/Controllers/TagSettingViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/ModalViews/TagDeleteModalView.swift
Labels: enhancement, code-review

#102 Feature/show plan
  EZY.xcodeproj/project.pbxproj
  EZY/Assets.xcassets/EZY_EmptyImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_EmptyImage.imageset/EZY_emptyImage.svg
  EZY/Assets.xcassets/EZY_InquiryImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_InquiryImage.imageset/Danger Triangle.svg
  EZY/Assets.xcassets/EZY_OnePersonImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_OnePersonImage.imageset/Profile.svg
  EZY/Controllers/ShowPlanViewController.swift
  EZY/Controllers/TagManagementViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/ModalViews/PlanCompleteModalView.swift
  EZY/Views/ScheduleTimeTableView.swift
  EZY/Views/ScheduleTypeCollectionView.swift
  EZY/Views/TableViewCells/ScheduleTimeTableViewCell.swift
Labels: enhancement, code-review

#115 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/ErrandDetailsViewController.swift
  EZY/Controllers/MoreAlarmModelViewController.swift
  EZY/Controllers/MoreCalendarModalsViewController.swift
  EZY/Controllers/MorePeopleToDo.swift
  EZY/Views/AddScheduleModalBtn .swift
  EZY/Views/AlarmDatePickerView.swift
  EZY/Views/CollectionViewCells/AlarmSettingCell.swift
  EZY/Views/CollectionViewCells/ErrandPeopoleChooseAfterCell.swift
  EZY/Views/CollectionViewCells/TagCell.swift
  EZY/Views/CollectionViewCells/WhatAboutPeopleLikeThisCell.swift
  EZY/Views/CollectionViewCells/WhoShouldIAskCell.swift
  EZY/Views/CustomData.swift
  EZY/Views/ErrandInputContainterTextField.swift
  EZY/Views/GroupSearchTextfield.swift
  EZY/Views/NotFoundUser.swift
  EZY/Views/SearchTableView.swift
  EZY/Views/SendUser.swift
  EZY/Views/TableViewCells/SearchTableCell.swift
  EZY/Views/inputContainerErrandTextView.swift
  Podfile.lock
Labels: bug, urgent, code-review, hotfix, complete

#88 Feature/push notification
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/ErrandCalendarViewController.swift
  EZY/Controllers/PersonalCalendarViewController.swift
  EZY/Controllers/PushNotificationManagementViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Utils/Extension.swift
  EZY/Utils/Utilities.swift
Labels: duplicate, code-review

#118 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/ErrandDetailsViewController.swift
  EZY/Controllers/LoginViewController.swift
  EZY/Controllers/MoreAlarmModelViewController.swift
  EZY/Controllers/MoreCalendarModalsViewController.swift
  EZY/Controllers/MorePeopleToDo.swift
  EZY/Models/Model.swift
  EZY/ViewModels/SearchViewModel.swift
  EZY/Views/AddScheduleModalBtn .swift
  EZY/Views/AdditionalButton.swift
  EZY/Views/AlarmDatePickerView.swift
  EZY/Views/AlertButton.swift
  EZY/Views/CollectionViewCells/AlarmSettingCell.swift
  EZY/Views/CollectionViewCells/ErrandPeopoleChooseAfterCell.swift
  EZY/Views/CollectionViewCells/TagCell.swift
  EZY/Views/CollectionViewCells/WhatAboutPeopleLikeThisCell.swift
  EZY/Views/CollectionViewCells/WhoShouldIAskCell.swift
  EZY/Views/CustomBtn.swift
  EZY/Views/CustomData.swift
  EZY/Views/CustomTextField.swift
  EZY/Views/ErrandInputContainterTextField.swift
  EZY/Views/ExplanationContainerTextView.swift
  EZY/Views/GroupSearchTextfield.swift
  EZY/Views/MoreCalendarBtn.swift
  EZY/Views/MoreCalendarModalsButton .swift
  EZY/Views/NotFoundUser.swift
  EZY/Views/OneAlertButton.swift
  EZY/Views/SearchTableView.swift
  EZY/Views/SendUser.swift
  EZY/Views/TableViewCells/SearchTableCell.swift
  EZY/Views/TitleContainerTextFieldView.swift
  EZY/Views/inputContainerErrandTextView.swift
Labels: bug, code-review, complete

#119 [DELETE] PersonCalendarView Cell data & ErrandCalendarViewController …
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/ErrandCalendarViewController.swift
  EZY/Controllers/PersonalCalendarViewController.swift
  EZY/Controllers/PushNotificationManagementViewController.swift
  EZY/Controllers/TeamCalendarViewController.swift
Labels: bug, duplicate

#122 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/ErrandDetailsViewController.swift
  EZY/Controllers/MoreAlarmModelViewController.swift
  EZY/Controllers/MoreCalendarModalsViewController.swift
  EZY/Controllers/MorePeopleToDo.swift
  EZY/Views/AddScheduleModalBtn .swift
  EZY/Views/AlarmDatePickerView.swift
  EZY/Views/CollectionViewCells/AlarmSettingCell.swift
  EZY/Views/ErrandInputContainterTextField.swift
  EZY/Views/ExplanationContainerTextView.swift
  EZY/Views/GroupSearchTextfield.swift
  EZY/Views/OneAlertButton.swift
  EZY/Views/TitleContainerTextFieldView.swift
  EZY/Views/inputContainerErrandTextView.swift
  Podfile
  Podfile.lock
Labels: bug, duplicate, complete

#125 Feature/show plan
  EZY/Controllers/ShowPlanViewController.swift
Labels: inComplete

#126 Feature/setting
  EZY/Controllers/SettingViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/TableViewCells/SettingTableViewCell.swift
Labels: complete

#124 [CREATE] I used Stack View to reduce the code
  EZY/Controllers/PushNotificationManagementViewController.swift
  Podfile.lock
Labels: documentation, code-review, complete

#127 Feature/additional
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/PushNotificationManagementViewController.swift
  EZY/Models/ManagementbtnModel.swift
  EZY/Views/AlarmManagementButton.swift
Labels: documentation, code-review, complete

#128 Feature/notification
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/NotificationViewController.swift
  EZY/Controllers/PlanRequestRespondingViewController.swift
  EZY/Resources/AppDelegate.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/TableViewCells/NotificationTableViewCell.swift
Labels: complete

#129 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/MoreAlarmModelViewController.swift
  EZY/Controllers/MorePeopleToDo.swift
  EZY/Models/Model.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/AddScheduleModalBtn .swift
  EZY/Views/AlarmDatePickerView.swift
Labels: bug, documentation, code-review, complete

#132 Feature/personal plan change
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/PersonalPlanChangeViewController.swift
  EZY/Views/ModalViews/SelectCalendarModalView.swift
  EZY/Views/ModalViews/SelectLocationModalView.swift
  EZY/Views/ModalViews/SelectTimeModalView.swift
  EZY/Views/ModalViews/TagAddModalView.swift
Labels: urgent, code-review, complete

#134 [UPDATE] rightButton layout changed
  EZY/Resources/SceneDelegate.swift
  EZY/Views/TableViewCells/SettingTableViewCell.swift
Labels: complete

#133 Feature/change
  EZY/Controllers/ChangeIdAfterLoginViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: code-review, complete

#136 Feature/change passward
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/ChangePasswardAfterLoginViewController.swift
  EZY/Controllers/ChangePasswardPhoneNumAfterLoginViewController.swift
Labels: urgent, code-review, complete
