Repository neulsom-EZY/EZY-ios, pull requests merged in 2021-11, with the labels that each got.

#157 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Assets.xcassets/EZY_Fast_car.imageset/Contents.json
  EZY/Assets.xcassets/EZY_Fast_car.imageset/undraw_fast_car_p4cu 1.svg
  EZY/Controllers/LogoutViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/LogoutCustomBtn.swift
Labels: documentation, duplicate, code-review, complete

#162 README
  README.md
  READMEData/EZY.svg
Labels: hotfix, complete

#163 README
  README.md
  READMEData/EZY.svg
Labels: complete

#166 Feature/personal plan change
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/MyToDo/ChangeMyTodoViewController.swift
  EZY/Controllers/Features/Setting/SettingFeatures/TagAddModalViewController.swift
Labels: complete

#168 Feature/location
  EZY/Assets.xcassets/EZY_SearchButtonImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_SearchButtonImage.imageset/search.svg
  EZY/Controllers/Features/Location/SelectLocationViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: complete

#165 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/Errand/AddErrandViewController.swift
  EZY/Controllers/Features/Main/ShowPlanViewController.swift
  EZY/Controllers/Features/MyToDo/AddMyToDoViewController.swift
  EZY/Controllers/Features/MyToDo/ChangeMyTodoViewController.swift
  EZY/Controllers/Modal/BaseModal/BaseModal.swift
  EZY/Controllers/Modal/CalendarAddModelViewController.swift
  EZY/Controllers/Modal/MoreAlarmModelViewController.swift
  EZY/Controllers/Modal/MoreCalendarModalsViewController.swift
  EZY/Controllers/Modal/TimeAddModalViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: documentation, duplicate, code-review, complete

#170 Feature/phone num change
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/MyToDo/ChangeMyTodoViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePhoneNumAuthCodeViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePhoneNumPutViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: urgent, complete

#171 Hotfix/list
  EZY.xcodeproj/project.pbxproj
  EZY/Utils/Extension.swift
  EZY/Views/View/ListTagView.swift
  EZY/Views/View/TableView/ScheduleTimeTableView.swift
Labels: hotfix, complete

#169 [CREATE] TagModal Background Gesture add
  EZY/Controllers/Features/MyToDo/ChangeMyTodoViewController.swift
  EZY/Controllers/Features/Setting/SettingFeatures/TagAddModalViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: documentation, duplicate, code-review, complete

#177 Feature/list
  EZY/Controllers/Features/Errand/ErrandDetailsViewController.swift
  EZY/Controllers/Features/Errand/ErrandListViewController.swift
  EZY/Controllers/Features/Errand/PlanRequestRespondingViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoListViewController.swift
  EZY/Controllers/Features/MyToDo/PersonalPlanDetailViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/View/ListTagView.swift
Labels: complete

#180 Hotfix/user info
  EZY/Controllers/SignUp/SignUpPhoneNumViewController.swift
  EZY/Controllers/UserInfoChange/BeforeLogin/NewNicknamePhoneNumViewController.swift
Labels: hotfix, complete

#181 Feature/list
  EZY/Controllers/Features/Errand/ErrandListViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoDetailViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoListViewController.swift
Labels: complete

#182 Feature/list
  EZY/Controllers/Features/Errand/ErrandDetailsViewController.swift
  EZY/Controllers/Features/Errand/ErrandListViewController.swift
  EZY/Controllers/Features/Errand/PlanRequestRespondingViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoDetailViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoListViewController.swift
Labels: urgent, code-review, complete

#183 Feature/personal plan change
  EZY/Controllers/Features/Errand/PlanRequestRespondingViewController.swift
  EZY/Controllers/Features/Main/ShowPlanViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoDetailViewController.swift
  EZY/Controllers/Modal/BasicModalViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/TableViewCells/NotificationTableViewCell.swift
Labels: code-review, complete

#184 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/Errand/AddErrandViewController.swift
  EZY/Controllers/Features/Errand/ErrandDetailsViewController.swift
  EZY/Controllers/Features/Errand/ErrandList/ErrandListItemTableViewCell.swift
  EZY/Controllers/Features/Errand/ErrandList/ErrandListTableViewCell.swift
  EZY/Controllers/Features/Errand/ErrandList/reErrandListViewController.swift
  EZY/Controllers/Features/Errand/MorePeopleToDo.swift
  EZY/Controllers/Features/Location/SelectLocationViewController.swift
  EZY/Controllers/Features/Setting/SettingFeatures/WithdrawalViewController.swift
  EZY/Controllers/Modal/BasicModalViewController.swift
  EZY/Models/KakaoPlaeDataModel/kakaoPlaceDataModel.swift
  EZY/Networking/NetWorkResult.swift
  EZY/Services/KakaoPlaceSearchService/KakaoPlaceSearchAPI.swift
  EZY/Utils/Extension.swift
  EZY/Views/TableViewCells/LocationTableViewCell.swift
  Podfile
  Podfile.lock
Labels: documentation, complete

#185 Feature/personal plan change
  EZY/Controllers/Features/Errand/PlanRequestRespondingViewController.swift
  EZY/Controllers/Features/MyToDo/AddOrChangeMyTodoViewController.swift
  EZY/Controllers/Features/MyToDo/MyToDoDetailViewController.swift
  EZY/Resources/AppDelegate.swift
  EZY/Resources/SceneDelegate.swift
Labels: code-review, complete

#186 Feature/sign up
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/Location/SelectLocationViewController.swift
  EZY/Controllers/LogIn/LoginViewController.swift
  EZY/Controllers/SignUp/SignUpAuthCodeViewController.swift
  EZY/Controllers/SignUp/SignUpNicknameViewController.swift
  EZY/Controllers/SignUp/SignUpPasswordViewController.swift
  EZY/Controllers/SignUp/SignUpPhoneNumViewController.swift
  EZY/Controllers/SignUp/SignUpTermsViewController.swift
  EZY/Models/UserModel.swift
  EZY/Networking/API.swift
  EZY/Networking/Config.swift
  EZY/Networking/NetWorkResult.swift
  EZY/Resources/AppDelegate.swift
  EZY/Resources/SceneDelegate.swift
Labels: urgent, code-review, complete

#187 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/Errand/AddErrandViewController.swift
  EZY/Controllers/Features/Errand/ErrandDetailsViewController.swift
  EZY/Controllers/Features/Errand/ErrandList/ErrandListItemTableViewCell.swift
  EZY/Controllers/Features/Errand/ErrandList/reErrandListViewController.swift
  EZY/Controllers/Features/Errand/ErrandListViewController.swift
  EZY/Controllers/Features/Errand/MorePeopleToDo.swift
  EZY/Controllers/Features/Errand/PlanRequestRespondingViewController.swift
  EZY/Controllers/Features/Location/SelectLocationViewController.swift
  EZY/Controllers/Features/Setting/SettingFeatures/LogoutViewController.swift
  EZY/Controllers/Modal/MoreAlarmModelViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Services/KakaoPlaceSearchService/KakaoPlaceSearchAPI.swift
  EZY/Utils/TokenUtils.swift
  EZY/ViewModels/KakaoPlaceViewModel.swift
  EZY/ViewModels/SearchViewModel.swift
  EZY/Views/CollectionViewCells/ErrandList/ErrandListItemTableViewCell.swift
  EZY/Views/CollectionViewCells/ErrandList/ErrandListTableViewCell.swift
  EZY/Views/View/NoPlaceView.swift
Labels: documentation, duplicate, code-review, complete

#188 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Resources/SceneDelegate.swift
  EZY/Services/API/APIService.swift
  EZY/Services/KakaoPlaceSearchService/KakaoPlaceSearchAPI.swift
Labels: documentation, duplicate, code-review, complete

#190 [UPDATE] List Merge
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/Errand/ErrandListViewController.swift
  EZY/Controllers/Features/Errand/MorePeopleToDo.swift
  EZY/Models/Errand/ErrandEntireModel.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Services/API/APIService.swift
Labels: documentation, duplicate

#192 Merge Fix
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/Features/Setting/SettingViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePasswordAfterLoginViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePasswordAuthCodeAfterLoginViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePasswordNicknameViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePasswordPhoneNumAfterLoginViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePhoneNumAuthCodeViewController.swift
  EZY/Controllers/UserInfoChange/AfterLogin/ChangePhoneNumPhoneNumViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/View/TopView.swift
Labels: urgent
