Repository neulsom-EZY/EZY-ios, pull requests merged in 2021-10, with the labels that each got.

#137 Feature/tag setting
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/ChangePasswardPhoneNumAfterLoginViewController.swift
  EZY/Controllers/SignUpNicknameViewController.swift
  EZY/Controllers/TagManagementViewController.swift
  EZY/Controllers/TagSettingViewController.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Utils/Extension.swift
  EZY/Views/CollectionViewCells/TagColorCollectionViewCell.swift
  EZY/Views/ModalViews/TagAddModalView.swift
  EZY/Views/TableViewCells/TagTableViewCell.swift
Labels: complete

#139 notification UI changed
  EZY/Assets.xcassets/EZY_NotificationNoImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_NotificationNoImage.imageset/NotificationNoImage.svg
  EZY/Controllers/NotificationViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: complete

#141 [UPDATE] Fix Button Layout
  EZY/Controllers/SignUpNicknameViewController.swift
  Podfile.lock
Labels: urgent, hotfix, complete

#142 [UPDATE] private function
  EZY/Controllers/LoginViewController.swift
  EZY/Controllers/NewNicknamePhoneNumViewController.swift
  EZY/Controllers/NewNicknamePutViewController.swift
  EZY/Controllers/NewPasswordPhoneNumViewController.swift
  EZY/Controllers/NewPasswordPutViewController.swift
  EZY/Controllers/SignUpNicknameViewController.swift
  EZY/Controllers/SignUpPasswordViewController.swift
  EZY/Controllers/SignUpPhoneNumViewController.swift
  EZY/Controllers/SignUpTermsViewController.swift
Labels: urgent, complete

#146 KeyboardType Setting
  EZY/Controllers/LoginViewController.swift
  EZY/Controllers/NewNicknamePhoneNumViewController.swift
  EZY/Controllers/NewNicknamePutViewController.swift
  EZY/Controllers/NewPasswordPhoneNumViewController.swift
  EZY/Controllers/NewPasswordPutViewController.swift
  EZY/Controllers/SignUpNicknameViewController.swift
  EZY/Controllers/SignUpPasswordViewController.swift
  EZY/Controllers/SignUpPhoneNumViewController.swift
Labels: urgent, complete

#147 Feature/code clean
  EZY/Controllers/ChangeIdAfterLoginViewController.swift
  EZY/Controllers/MoreCalendarModalsViewController.swift
  EZY/Controllers/NotificationViewController.swift
  EZY/Controllers/ShowPlanViewController.swift
  EZY/Resources/AppDelegate.swift
  EZY/Resources/SceneDelegate.swift
  Podfile.lock
Labels: urgent, code-review, complete

#149 Error Fix
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/ErrandDetailsViewController.swift
  EZY/Controllers/ShowPlanViewController.swift
  EZY/Models/Model.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/AlertButton.swift
  EZY/Views/CalendarAlertBtn.swift
  EZY/Views/SendUser.swift
  EZY/Views/TableViewCells/SearchTableCell.swift
Labels: bug, documentation, duplicate, complete

#150 Feature/additional
  EZY/Controllers/MoreCalendarModalsViewController.swift
  EZY/Controllers/ShowPlanViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: documentation, duplicate

#151 Feature/push notification
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/ErrandCalendarViewController.swift
  EZY/Controllers/PersonalCalendarViewController.swift
  EZY/Controllers/PushNotificationManagementViewController.swift
  EZY/Resources/SceneDelegate.swift
Labels: documentation, duplicate, code-review, complete

#153 Feature/additional
  EZY.xcodeproj/project.pbxproj
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/AddMyToDoViewController.swift
  EZY/Controllers/ErrandDetailsViewController.swift
  EZY/Controllers/MorePeopleToDo.swift
  EZY/Models/CollectionViewModel.swift
  EZY/Views/CollectionViewCells/AlarmSettingCell.swift
  EZY/Views/CollectionViewCells/TagCell.swift
  EZY/Views/NotFoundUser.swift
  EZY/Views/SearchTableView.swift
  EZY/Views/TableViewCells/SearchTableCell.swift
Labels: documentation, duplicate

#152 Feature/personal plan change
  EZY.xcodeproj/project.pbxproj
  EZY/Assets.xcassets/EZY_SelectedNoSelectTagButtonImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_SelectedNoSelectTagButtonImage.imageset/흰색ㅌ.svg
  EZY/Assets.xcassets/EZY_SelectedTagAddButtonImage-1.imageset/Contents.json
  EZY/Assets.xcassets/EZY_SelectedTagAddButtonImage-1.imageset/선택된추가 버튼.svg
  EZY/Assets.xcassets/EZY_UnSelectedNoSelectTagButtonImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_UnSelectedNoSelectTagButtonImage.imageset/찐막회.svg
  EZY/Assets.xcassets/EZY_UnSelectedTagAddButtonImage.imageset/Contents.json
  EZY/Assets.xcassets/EZY_UnSelectedTagAddButtonImage.imageset/추가 버튼.svg
  EZY/Controllers/AddErrandViewController.swift
  EZY/Controllers/PersonalPlanChangeViewController.swift
  EZY/Controllers/ShowPlanViewController.swift
  EZY/Controllers/TagSettingViewController.swift
  EZY/Models/RepeatCollectionViewModel.swift
  EZY/Models/TagCollectionViewModel.swift
  EZY/Resources/SceneDelegate.swift
  EZY/Views/AlertButton.swift
  EZY/Views/CalendarBtn.swift
  EZY/Views/CollectionViewCells/DayCollectionViewCell.swift
  EZY/Views/CollectionViewCells/PersonalPlanAddRepeatDayCollectionViewCell.swift
  EZY/Views/CollectionViewCells/TagCollectionViewCell.swift
  EZY/Views/CollectionViewCells/WhoShouldIAskCell.swift
  EZY/Views/ModalViews/SelectCalendarModalView.swift
  EZY/Views/ModalViews/SelectTimeModalView.swift
  EZY/Views/ModalViews/TagAddModalView.swift
Labels: inComplete
